<?xml version="1.0" encoding="windows-1252"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://www.arrabiata.de/soap/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.arrabiata.de/soap/">
<types>
<xsd:schema targetNamespace="http://www.arrabiata.de/soap/">
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
</xsd:schema>
</types>
<message name="quadratRequest">
  <part name="a" type="xsd:int"/></message>
<message name="quadratResponse">
  <part name="quadrat" type="xsd:int"/></message>
<portType name="QuadratPortType">
  <operation name="quadrat">
    <input message="tns:quadratRequest"/>
    <output message="tns:quadratResponse"/>
  </operation>
</portType>
<binding name="QuadratBinding" type="tns:QuadratPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="quadrat">
    <soap:operation soapAction="http://localhost/php_zend_zert/uebungen/soap/soap_server.php/quadrat" style="rpc"/>
    <input><soap:body use="encoded" namespace="http://soapinterop.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="http://soapinterop.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="Quadrat">
  <port name="QuadratPort" binding="tns:QuadratBinding">
    <soap:address location="http://localhost/php_zend_zert/uebungen/soap/soap_server.php"/>
  </port>
</service>
</definitions>